apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: migrations-volume
          configMap:
            name: api-migrations
      initContainers:
        - name: db-migration
          image: postgres:15-alpine
          command: ['sh', '-c', 'echo "Waiting for PostgreSQL to become available..." && until pg_isready -h $PG_HOST -p $PG_PORT -U $PG_USER; do sleep 2; done; echo "PostgreSQL is available. Running migrations..." && psql -h $PG_HOST -p $PG_PORT -U $PG_USER -d $PG_DBNAME -f /migrations/001_initial_schema.sql']
          env:
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbHost
            - name: PG_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbPort
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserName
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserPass
            - name: PG_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbName
          volumeMounts:
            - name: migrations-volume
              mountPath: /migrations
        - name: wait-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z postgres-headless 5432; do echo "waiting for postgres"; sleep 2; done;']
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z rabbitmq-headless 5672; do echo "waiting for rabbitmq"; sleep 2; done;']
      containers:
        - name: api
          image: ghcr.io/yyvfuruta/driva-ps-api:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: apiPort

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbPort
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserName
            - name: DB_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserPass
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbName

            - name: RABBITMQ_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserName
            - name: RABBITMQ_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserPass
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqHost
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqPort

            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app
                  key: authToken

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: redisHost
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: redisPort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker1
  labels:
    app: worker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker1
  template:
    metadata:
      labels:
        app: worker1
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z postgres-headless 5432; do echo "waiting for postgres"; sleep 2; done;']
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z rabbitmq-headless 5672; do echo "waiting for rabbitmq"; sleep 2; done;']
      containers:
        - name: worker1
          image: ghcr.io/yyvfuruta/driva-ps-worker1:main
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbPort
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserName
            - name: DB_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserPass
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbName
            - name: RABBITMQ_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserName
            - name: RABBITMQ_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserPass
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqHost
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqPort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker2
  labels:
    app: worker2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker2
  template:
    metadata:
      labels:
        app: worker2
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z postgres-headless 5432; do echo "waiting for postgres"; sleep 2; done;']
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z rabbitmq-headless 5672; do echo "waiting for rabbitmq"; sleep 2; done;']
      containers:
        - name: worker2
          image: ghcr.io/yyvfuruta/driva-ps-worker2:main
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbPort
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserName
            - name: DB_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserPass
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbName
            - name: RABBITMQ_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserName
            - name: RABBITMQ_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserPass
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqHost
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqPort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker3
  labels:
    app: worker3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker3
  template:
    metadata:
      labels:
        app: worker3
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z postgres-headless 5432; do echo "waiting for postgres"; sleep 2; done;']
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z rabbitmq-headless 5672; do echo "waiting for rabbitmq"; sleep 2; done;']
      containers:
        - name: worker3
          image: ghcr.io/yyvfuruta/driva-ps-worker3:main
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbPort
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserName
            - name: DB_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserPass
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbName
            - name: RABBITMQ_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserName
            - name: RABBITMQ_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserPass
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqHost
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqPort
