apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z postgres-headless 5432; do echo "waiting for postgres"; sleep 2; done;']
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z rabbitmq-headless 5672; do echo "waiting for rabbitmq"; sleep 2; done;']
      containers:
        - name: api
          image: ghcr.io/yyvfuruta/driva-ps/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: apiPort

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbPort
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserName
            - name: DB_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserPass
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbName

            - name: RABBITMQ_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserName
            - name: RABBITMQ_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserPass
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqHost
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqPort

            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app
                  key: authToken

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: redisHost
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: redisPort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker1
  labels:
    app: worker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker1
  template:
    metadata:
      labels:
        app: worker1
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z postgres-headless 5432; do echo "waiting for postgres"; sleep 2; done;']
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z rabbitmq-headless 5672; do echo "waiting for rabbitmq"; sleep 2; done;']
      containers:
        - name: worker1
          image: ghcr.io/yyvfuruta/driva-ps/worker1:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbPort
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserName
            - name: DB_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserPass
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbName
            - name: RABBITMQ_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserName
            - name: RABBITMQ_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserPass
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqHost
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqPort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker2
  labels:
    app: worker2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker2
  template:
    metadata:
      labels:
        app: worker2
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z postgres-headless 5432; do echo "waiting for postgres"; sleep 2; done;']
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z rabbitmq-headless 5672; do echo "waiting for rabbitmq"; sleep 2; done;']
      containers:
        - name: worker2
          image: ghcr.io/yyvfuruta/driva-ps/worker2:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbPort
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserName
            - name: DB_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserPass
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbName
            - name: RABBITMQ_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserName
            - name: RABBITMQ_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserPass
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqHost
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqPort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker3
  labels:
    app: worker3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker3
  template:
    metadata:
      labels:
        app: worker3
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z postgres-headless 5432; do echo "waiting for postgres"; sleep 2; done;']
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z rabbitmq-headless 5672; do echo "waiting for rabbitmq"; sleep 2; done;']
      containers:
        - name: worker3
          image: ghcr.io/yyvfuruta/driva-ps/worker3:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbPort
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserName
            - name: DB_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: dbUserPass
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: dbName
            - name: RABBITMQ_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserName
            - name: RABBITMQ_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: app
                  key: rabbitmqUserPass
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqHost
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rabbitmqPort
