apiVersion: v1
stringData:
  authToken: cecd24ae-bbd6-11f0-bbc0-2c0da77e0ef5
  dbUserPass: asdf
  dbUserName: admin
  rabbitmqUserPass: asdf
  rabbitmqUserName: admin
kind: Secret
metadata:
  name: app
type: Opaque
